### ISSUE TITLE
Preview fails when author is missing / HTTP 500

### ISSUE THREAD

**Issue by cweiske** [aaronpk/Quill#83]
When typing in "https://cweiske.de/" as reply-to URL, the preview fails with a HTTP status code 500.

https://quill.p3k.io/reply/preview?url=https%3A%2F%2Fcweiske.de

```
<html><head><title>Slim Application Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Slim Application Error</h1><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> ErrorException</div><div><strong>Code:</strong> 2</div><div><strong>Message:</strong> array_key_exists() expects parameter 2 to be array, boolean given</div><div><strong>File:</strong> /web/sites/quill.p3k.io/controllers/controllers.php</div><div><strong>Line:</strong> 730</div><h2>Trace</h2><pre>#0 [internal function]: Slim\Slim::handleErrors(2, 'array_key_exist...', '/web/sites/quil...', 730, Array)
#1 /web/sites/quill.p3k.io/controllers/controllers.php(730): array_key_exists('author', false)
#2 [internal function]: {closure}()
#3 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Router.php(172): call_user_func_array(Object(Closure), Array)
#4 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch(Object(Slim\Route))
#5 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#6 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#7 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#9 /web/sites/quill.p3k.io/public/index.php(25): Slim\Slim->run()
#10 {main}</pre></body></html>
```

**Comment by aaronpk** [comment]
😲
